version: 0.0
os: linux
files:
  #- source: app
    #destination: /var/www/html/app
  #- source: bootstrap
    #destination: /var/www/html/bootstrap
  #- source: config
    #destination: /var/www/html/config
  #- source: database
    #destination: /var/www/html/database
  #- source: public
    #destination: /var/www/html/public
  #- source: resources
    #destination: /var/www/html/resources
  #- source: routes
    #destination: /var/www/html/routes
  #- source: storage
    #destination: /var/www/html/storage
  #- source: tests
    #destination: /var/www/html/tests
  - source: /
    destination: /var/www/html
hooks:
  #BeforeInstall:
    #- location: scripts/install_dependencies
    #  timeout: 300
    #  runas: root
    #- location: scripts/start_server
    #  timeout: 300
    #  runas: root
  #ApplicationStop:
    #- location: scripts/stop_server
    #  timeout: 300
    #  runas: root
